const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Behaviors.wrap,
		C3.Plugins.Button,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.FadeVolume
	];
};
self.C3_JsPropNameTable = [
	{PlanoEmBlocos: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{jogador: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Mouse: 0},
	{vida: 0},
	{monstro: 0},
	{Esmaecer: 0},
	{explosão: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{GameOver: 0},
	{Teclado: 0},
	{vida_fantasma: 0},
	{DarAVolta: 0},
	{Fantasma: 0},
	{Pontuação_Fantasmas: 0},
	{sprites: 0},
	{iniciar: 0},
	{FonteDeSprites: 0},
	{Texto: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{vida_goblin: 0},
	{Goblin: 0},
	{Áudio: 0},
	{Pontos: 0},
	{pontos_fantasma: 0}
];

self.InstanceType = {
	PlanoEmBlocos: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	Projétil: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	monstro: class extends self.ISpriteInstance {},
	explosão: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	Fantasma: class extends self.ISpriteInstance {},
	Pontuação_Fantasmas: class extends self.ITextInstance {},
	sprites: class extends self.ISpriteInstance {},
	iniciar: class extends self.IButtonInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Goblin: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}